# SPDX-License-Identifier: CERN-OHL-S-2.0
"""Build everything: STL + 4-view PNG render per part + DEC-23 fit check.

Usage:  uv run python -m koala_hardware.export [name-filter]
Outputs: build/stl/*.stl, build/renders/*.png, build/manifest.txt
The build FAILS (exit 1) if any part exceeds the print bed in its declared
print orientation (DEC-09 / DEC-23).
"""
import sys
import pathlib
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
import numpy as np
import trimesh
from build123d import export_stl, mirror, Plane
from . import params as P
from . import printability as PR
from .parts import all_builders

ROOT = pathlib.Path(__file__).resolve().parents[2]
STL = ROOT / "build" / "stl"
REN = ROOT / "build" / "renders"


def render(mesh: trimesh.Trimesh, path: pathlib.Path, title: str):
    fig = plt.figure(figsize=(10, 8))
    views = [(30, -60, "iso"), (0, -90, "side"), (0, 0, "front"), (90, -90, "top")]
    for i, (elev, azim, label) in enumerate(views, 1):
        ax = fig.add_subplot(2, 2, i, projection="3d")
        tris = mesh.vertices[mesh.faces]
        pc = Poly3DCollection(tris, alpha=1.0, facecolor="#8fb4d9",
                              edgecolor="#2a4a6a", linewidth=0.15)
        ax.add_collection3d(pc)
        lo, hi = mesh.bounds
        c, r = (lo + hi) / 2, max(hi - lo) / 2 * 1.1
        ax.set_xlim(c[0] - r, c[0] + r)
        ax.set_ylim(c[1] - r, c[1] + r)
        ax.set_zlim(c[2] - r, c[2] + r)
        ax.set_title(label, fontsize=9)
        ax.view_init(elev=elev, azim=azim)
        ax.set_axis_off()
    fig.suptitle(title)
    fig.tight_layout()
    fig.savefig(path, dpi=90)
    plt.close(fig)


def prune(current: set[str]) -> list[str]:
    """Delete outputs for parts that no longer exist under that name.

    A renamed part otherwise leaves its old STL sitting beside the new one,
    and a stale file slices just as happily as a current one.
    """
    keep = current | {"assembly"}
    removed = []
    for folder, ext in ((STL, ".stl"), (REN, ".png")):
        for f in folder.glob(f"*{ext}"):
            if f.stem not in keep:
                f.unlink()
                removed.append(f.name)
    return removed


PETG_DENSITY = 1.27          # g/cm3 - solid PETG
BOM_BEGIN = "<!-- BEGIN GENERATED: printed parts -->"
BOM_END = "<!-- END GENERATED -->"


def write_bom(bom: list[dict]) -> bool:
    """Rewrite the generated block in docs/bom.md. Returns False if the doc or
    its markers are missing (a filtered build simply skips this)."""
    doc = ROOT.parent / "docs" / "bom.md"
    if not doc.exists():
        return False
    text = doc.read_text()
    if BOM_BEGIN not in text or BOM_END not in text:
        return False

    rows = ["| Part | Qty | Size (mm) | Volume | PETG solid | Support-free |",
            "|------|-----|-----------|--------|-----------|--------------|"]
    tot_vol = tot_qty = 0
    for r in sorted(bom, key=lambda r: (r["name"].startswith("coupon"),
                                        r["name"])):
        sx, sy, sz = r["size"]
        mark = "yes" if r["ok"] else "**NO**"
        if r["ok"] and r["overhang"] > 0:
            mark = f"yes ({r['overhang']:.0f} mm2)"
        rows.append(f"| `{r['name']}` | {r['qty']} | {sx:.0f} x {sy:.0f} x "
                    f"{sz:.0f} | {r['vol']:.0f} cm3 | "
                    f"{r['vol'] * PETG_DENSITY * r['qty']:.0f} g | {mark} |")
        if not r["name"].startswith("coupon"):
            tot_vol += r["vol"] * r["qty"]
            tot_qty += r["qty"]
    rows.append(f"| **Structural total** | **{tot_qty}** | | "
                f"**{tot_vol:.0f} cm3** | **{tot_vol * PETG_DENSITY:.0f} g** | |")

    block = (f"{BOM_BEGIN}\n\n*Generated by `koala_hardware.export` - do not "
             f"hand-edit. Volumes are solid geometry; actual filament use is "
             f"lower with infill. Coupons excluded from the total.*\n\n"
             + "\n".join(rows) + f"\n\n{BOM_END}")
    start = text.index(BOM_BEGIN)
    end = text.index(BOM_END) + len(BOM_END)
    doc.write_text(text[:start] + block + text[end:])
    return True


def main():
    name_filter = sys.argv[1] if len(sys.argv) > 1 else ""
    STL.mkdir(parents=True, exist_ok=True)
    REN.mkdir(parents=True, exist_ok=True)
    failures, lines = [], []

    built, bom = [], []
    for builder in all_builders():
        spec = builder()
        handed = spec.get("handed", False)
        qty = spec.get("qty", 1)
        oriented = spec["orientation"] * spec["part"]
        # A handed part needs a real mirrored STL, not "remember to flip it in
        # the slicer". Mirroring about a vertical plane preserves Z, so the
        # print orientation and its metrics carry over unchanged.
        variants = ([(f"{spec['name']}_right", oriented),
                     (f"{spec['name']}_left", mirror(oriented, Plane.XZ))]
                    if handed else [(spec["name"], oriented)])
        built += [n for n, _ in variants]
        if name_filter and name_filter not in spec["name"]:
            continue

        for name, solid in variants:
            bb = solid.bounding_box()
            size = (bb.size.X, bb.size.Y, bb.size.Z)
            fits = (size[0] <= P.BED_X and size[1] <= P.BED_Y
                    and size[2] <= P.BED_Z)
            stl_path = STL / f"{name}.stl"
            export_stl(solid, str(stl_path))
            mesh = trimesh.load(stl_path)
            render(mesh, REN / f"{name}.png", name)
            printable, verdict, m = PR.check(mesh)
            ok = fits and printable
            status = "OK  " if ok else "FAIL"
            line = (f"[{status}] {name:22s} {size[0]:6.1f} x {size[1]:6.1f} x "
                    f"{size[2]:6.1f} mm  {mesh.volume / 1000:6.1f} cm3  "
                    f"bed {m['bed_area']:7.0f}  overhang "
                    f"{m['overhang_area']:7.0f}"
                    f"  {'' if fits else 'EXCEEDS BED; '}{verdict}")
            print(line)
            if not printable:
                alts = ", ".join(f"{n}(oh {o:.0f}, bed {b:.0f})"
                                 for n, o, b in PR.best_orientations(mesh))
                print(f"         better orientations: {alts}")
                line += f"\n    better orientations: {alts}"
            lines.append(line + "\n    " + spec["notes"])
            bom.append({"name": name, "qty": qty, "size": size,
                        "vol": mesh.volume / 1000, "ok": ok,
                        "overhang": m["overhang_area"]})
            if not ok:
                failures.append(name)

    orphans = prune(set(built))
    if orphans:
        print(f"\npruned stale output for renamed/removed parts: "
              f"{', '.join(sorted(orphans))}")

    if not name_filter and write_bom(bom):
        print("updated docs/bom.md (printed parts)")

    (ROOT / "build" / "manifest.txt").write_text("\n".join(lines) + "\n")
    if failures:
        print(f"\nFAILURES (DEC-09 bed fit / DEC-24 support-free): {failures}")
        sys.exit(1)


if __name__ == "__main__":
    main()
