"""Crude MuJoCo MJCF of the four-foot walking build (DEC-62), from the CAD's kinematic frames.

    uv run python -m koala_hardware.mjcf            # writes sim/koala_walking_crude.xml + .json
    uv run python -m koala_hardware.mjcf OUT.xml

Reads the walking pose, joint centres and axes and link solid volumes from this package.
Geometry is capsules, a box and spheres, not the printed meshes. Masses are solid-PETG/TPU
upper bounds plus SERVO_MASS per servo; no battery, electronics, head or cables. The actuator
is Open Duck's BAM fit of the 7.4 V STS3215 as a placeholder until the 12 V unit is identified
(wk-robotics docs/status.md, "A sim model of koala-bot's four-foot build"). Nothing here is
verified against hardware. Loading and stepping the output needs MuJoCo, which is not a
dependency of this package; see docs/architecture.md, Modelling & tooling.
"""
import json, sys, math
from pathlib import Path
from koala_hardware import assembly as A, body_plan as B, params as P
from koala_hardware.parts import links as L, front as F, foot_shank as FS, torso, pelvis, shoulder_mount as SM, e_tray

MM = 1e-3
PETG, TPU = 1.27, 1.2          # g/cm3, hardware/src/koala_hardware/export.py:70 (TPU provisional)
SERVO_G = P.SERVO_MASS         # 55 g [SPEC], params.py:44
# Shared-control clearance bounds in the walking pose (degrees, relative to the pose),
# docs/design/walking/viewer-endpoints.json "initial_pose_bounds.walking". These are
# sampled CAD clearances for ONE shared slider driving all limbs, not servo limits.
RANGE = {'pitch': (-43.5, 107.5), 'roll': (-16.0, 29.25), 'bend': (-61.25, 89.25)}
# Placeholder actuator: Open Duck's BAM fit of the 7.4 V STS3215
# (Open_Duck_Playground/.../open_duck_mini_v2.xml:45-49). 12 V fit is plan step 1.
SERVO_CLASS = dict(damping=0.56, frictionloss=0.068, armature=0.027, kp=13.37, force=3.23)

pose = B.poses()['walking']
jd = A.joint_data('walking')
g = lambda v: v * PETG  # cm3 -> g solid
vol = lambda s: s.volume / 1000.0
mass = {
    'torso_frame': g(vol(torso.solid())), 'root_socket': g(vol(pelvis.root_socket())),
    'shoulder_mount': g(vol(SM.solid())), 'e_tray': g(vol(e_tray.solid())),
    'hip_carrier': g(vol(L.carrier(False))), 'thigh': g(vol(L.upper_link(P.BODY_THIGH_MM, True))),
    'foot_shank': g(vol(FS.solid())), 'shoulder_carrier': g(vol(F.carrier())),
    'upper_arm': g(vol(F.upper_arm())), 'forearm': g(vol(F.forearm())),
    'pad': vol(L.front_pad()) * TPU,
}
torso_mass = mass['torso_frame'] + 4 * mass['root_socket'] + 2 * mass['shoulder_mount'] + mass['e_tray'] + 4 * SERVO_G

def v3(p): return ' '.join(f'{x*MM:.6f}' for x in p)
def ax(a): return ' '.join(f'{x:.6f}' for x in a)
def sub(a, b): return [x - y for x, y in zip(a, b)]

hip = (pose['rear'].root.x, 0.0, pose['rear'].root.z)          # torso body origin, world mm
theta = pose['body_angle']                                       # deg, spine above +X
spine_lo, spine_hi = torso.LOW, torso.TOP                        # body-frame Z extent of torso_frame
lines = []
w = lines.append
w(f'<mujoco model="koala_walking_crude">')
w('  <!-- CRUDE model generated by koala_hardware/mjcf.py from koala-bot CAD (walking pose). Primitive geoms, not print meshes. -->')
w(f'  <!-- masses: solid-PETG/TPU upper bounds x volume + {SERVO_G:g} g per servo [SPEC]; no battery, electronics, head, cables -->')
w('  <!-- joint ranges: shared-control clearance bounds from viewer-endpoints.json, NOT servo limits -->')
w('  <!-- actuator: Open Duck 7.4 V BAM placeholder, NOT the 12 V unit -->')
w('  <!-- CAD "right" is +Y (params.py:303 body +Y right). With X forward / Z up that is the robot LEFT in a right-handed frame; names below follow the CAD. -->')
w('  <compiler angle="degree"/>')
w('  <option timestep="0.002"/>')
w('  <default>')
w('    <default class="sts3215">')
w(f'      <joint type="hinge" damping="{SERVO_CLASS["damping"]}" frictionloss="{SERVO_CLASS["frictionloss"]}" armature="{SERVO_CLASS["armature"]}" limited="true"/>')
w(f'      <position kp="{SERVO_CLASS["kp"]}" forcerange="-{SERVO_CLASS["force"]} {SERVO_CLASS["force"]}"/>')
w('    </default>')
w('    <default class="link"><geom type="capsule" contype="0" conaffinity="0" rgba="0.55 0.7 0.85 1"/></default>')
w('    <default class="foot"><geom type="sphere" contype="1" conaffinity="1" condim="3" friction="0.8" rgba="0.3 0.3 0.3 1"/></default>')
w('  </default>')
w('  <worldbody>')
w('    <light pos="0 0 2" dir="0 0 -1" directional="true"/>')
w('    <geom name="floor" type="plane" size="0 0 0.05" contype="1" conaffinity="1" friction="0.8" rgba="0.9 0.9 0.9 1"/>')
w(f'    <body name="torso" pos="{v3(hip)}">')
w('      <freejoint name="floating_base"/>')
w('      <site name="imu" pos="0.06 0 0.02"/>')
half = ((P.BODY_HEAD_LENGTH_MM * 0 + 82) / 2, P.TORSO_HALF_WIDTH, (spine_hi - spine_lo) / 2)   # 82 mm ventral depth = torso_frame bbox X
centre = (spine_lo + spine_hi) / 2
c = (centre * math.cos(math.radians(theta)), 0.0, centre * math.sin(math.radians(theta)))
w(f'      <geom name="torso_box" type="box" size="{v3(half)}" pos="{v3(c)}" euler="0 {90-theta:.4f} 0" mass="{torso_mass*1e-3:.4f}" contype="0" conaffinity="0" rgba="0.6 0.6 0.7 1"/>')
acts = []
for key, side, sname in (('rear', 1, 'right'), ('rear', -1, 'left'), ('front', 1, 'right'), ('front', -1, 'left')):
    d = jd[key]; limb = pose[key]
    m = lambda p: [p[0], side * p[1], p[2]]                       # mirror the canonical right side (assembly.py:163)
    roll_axis = [side * x for x in d['roll_axis']]                # mirrored roll: same axis, opposite sign (+ abducts both sides)
    y = P.BODY_SHOULDER_WIDTH_MM / 2 if key == 'front' else L.rear_axis_y()
    axle = [limb.axle.x, side * y, limb.axle.z]
    first, second = (('roll', 'pitch') if key == 'front' else ('pitch', 'roll'))
    j1, j2, j3 = m(d[first]), m(d[second]), m(d['bend'])
    prefix = f'{key}_{sname}'
    names = {'pitch': 'hip_pitch' if key == 'rear' else 'shoulder_pitch', 'roll': 'hip_roll' if key == 'rear' else 'shoulder_roll', 'bend': 'knee' if key == 'rear' else 'elbow'}
    carrier_m = (mass['hip_carrier'] if key == 'rear' else mass['shoulder_carrier']) + SERVO_G
    upper_m = (mass['thigh'] if key == 'rear' else mass['upper_arm']) + SERVO_G
    lower_m = mass['foot_shank'] if key == 'rear' else mass['forearm']
    r1, r2, r3 = 0.012, 0.014, 0.010
    # body 1: carrier (first joint)
    w(f'      <body name="{prefix}_carrier" pos="{v3(sub(j1, hip))}">')
    a1 = roll_axis if first == 'roll' else [0, 1, 0]
    w(f'        <joint name="{prefix}_{names[first]}" class="sts3215" axis="{ax(a1)}" range="{RANGE[first][0]} {RANGE[first][1]}"/>')
    w(f'        <geom class="link" size="{r1}" fromto="0 0 0 {v3(sub(j2, j1))}" mass="{carrier_m*1e-3:.4f}"/>')
    acts.append(f'{prefix}_{names[first]}')
    # body 2: upper link (second joint)
    w(f'        <body name="{prefix}_upper" pos="{v3(sub(j2, j1))}">')
    a2 = roll_axis if second == 'roll' else [0, 1, 0]
    w(f'          <joint name="{prefix}_{names[second]}" class="sts3215" axis="{ax(a2)}" range="{RANGE[second][0]} {RANGE[second][1]}"/>')
    w(f'          <geom class="link" size="{r2}" fromto="0 0 0 {v3(sub(j3, j2))}" mass="{upper_m*1e-3:.4f}"/>')
    acts.append(f'{prefix}_{names[second]}')
    # body 3: lower link + pad (bend joint)
    w(f'          <body name="{prefix}_lower" pos="{v3(sub(j3, j2))}">')
    w(f'            <joint name="{prefix}_{names["bend"]}" class="sts3215" axis="0 1 0" range="{RANGE["bend"][0]} {RANGE["bend"][1]}"/>')
    w(f'            <geom class="link" size="{r3}" fromto="0 0 0 {v3(sub(axle, j3))}" mass="{lower_m*1e-3:.4f}"/>')
    w(f'            <geom name="{prefix}_pad" class="foot" size="{P.BODY_FRONT_FOOT_RADIUS_MM*MM:.4f}" pos="{v3(sub(axle, j3))}" mass="{mass["pad"]*1e-3:.4f}"/>')
    w(f'            <site name="{prefix}_foot" pos="{v3(sub(axle, j3))}"/>')
    acts.append(f'{prefix}_{names["bend"]}')
    w('          </body>')
    w('        </body>')
    w('      </body>')
w('    </body>')
w('  </worldbody>')
w('  <actuator>')
for a in acts:
    w(f'    <position class="sts3215" name="{a}" joint="{a}" inheritrange="1"/>')
w('  </actuator>')
w('  <sensor>')
w('    <gyro site="imu" name="gyro"/><accelerometer site="imu" name="accelerometer"/><framezaxis objtype="site" objname="imu" name="upvector"/>')
for a in ('rear_right', 'rear_left', 'front_right', 'front_left'):
    w(f'    <framepos objtype="site" objname="{a}_foot" name="{a}_foot_pos"/>')
w('  </sensor>')
w('  <keyframe>')
w(f'    <key name="home" qpos="{v3(hip)} 1 0 0 0 {" ".join("0"*12)}" ctrl="{" ".join("0"*12)}"/>')
w('  </keyframe>')
w('</mujoco>')
out = sys.argv[1] if len(sys.argv) > 1 else str(Path(__file__).resolve().parents[2] / 'sim' / 'koala_walking_crude.xml')
Path(out).parent.mkdir(parents=True, exist_ok=True)
open(out, 'w').write('\n'.join(lines) + '\n')
json.dump({'mass_g': mass, 'torso_g': torso_mass, 'joints': jd, 'walking_pose': {k: (str(pose[k]) if k != 'body_angle' else pose[k]) for k in pose}},
          open(out.replace('.xml', '.json'), 'w'), indent=1)
print('wrote', out, '| link masses g:', {k: round(v, 1) for k, v in mass.items()}, '| torso g', round(torso_mass, 1))
